# java home on mac
export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home/

# export home bin to path
export PATH=~/bin:$PATH

# constant contact

# aliases
alias d1scapi="ssh c1-vmdjb146.roving.com"
alias d1sclp="ssh c1-vmdjb145.roving.com"
alias d1scui="ssh c1-vmdjb140.roving.com"
alias dochost="ssh constantcontact@192.168.96.69"
